#include "styles.h"

const QString On = "QPushButton:hover {"
                   "background-color: #88cc88;"
                   "color: #f66666;"
                   "border: 1px solid yellow;"
                   "border-radius: 3px;"
                   "width: 30px;"
                   "height: 15px;"
               "}"
               "QPushButton:!hover {"
                     "background-color: #88cc88;"
                     "color: #666666;"
                     "border: 1px solid gray;"
                     "border-radius: 3px;"
                     "width: 30px;"
                     "height: 15px;"
                "}"
             "QPushButton:pressed:!hover {"
               "background-color: #f66666;"
               "border: 1px solid gray;"
               "border-radius: 3px;"
               "width: 30px;"
               "height: 15px;"
               "}";

const QString Off = "QPushButton:hover {"
                    "background-color: #888888;"
                    "color: #ffFF66;"
                    "border: 1px solid yellow;"
                    "border-radius: 3px;"
                    "width: 30px;"
                "height: 15px;"
                  "}"
                  "QPushButton:!hover {"
                    "background-color: #888888;"
                    "border: 1px solid gray;"
                    "border-radius: 3px;"
                    "width: 30px;"
                "height: 15px;"
                    "}"
                "QPushButton:pressed {"
                  "background-color: #f88888;"
                  "border: 1px solid gray;"
                  "border-radius: 3px;"
                  "width: 30px;"
                  "height: 15px;"
                  "}";

const QString lineEditStyle = "QLineEdit { border-style: outset;"
                              " border-width: 2px;"
                              " border-radius: 10px; "
                              " border-color: gray;"
                              "}";
